language: node_js

node_js:
  - "10"
  - "8"

script:
  - npm install codecov -g
  - npm run lint
  - npm run test-ci
  - npm run coverage
  - npm run check-coverage
  - npm run report

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always